---
title: "ISSS608 Visual Analytics - DataViz Makeover 1"
description: |
  This is the submission for the DataViz Makeover 1.
author:
  - name: Louis Chong Jia Jun (louis.chong.2019@mitb.smu.edu.sg)
    url: https://www.linkedin.com/in/louis-chong-jia-jun
date: 01-19-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1.0 Critiques and Improvements of Data Visualisation

The Report on Labour Force in Singapore (https://stats.mom.gov.sg/Pages/Labour-Force-In-Singapore-2019.aspx) is a key annual report on Singapore's labour market. Below is a critique of the data visualisation on the resident labour force and how it could be improved. The data is available at https://stats.mom.gov.sg/Pages/Labour-Force-Tables2019.aspx, Table 5, Resident Labour Force Participation Rate by Age and Sex, 2009 - 2019 (June).

## Clarity

* By looking at the two lines in the data visualisation, we can clearly tell that the share of residents aged 55 & over in the labour force rose in 2019 as compared to 2009 and fell for residents aged 25 to 54. However, a line chart should not be used, as data was aggregated at each age range and we will imply that we can interpolate and find the value at each age.
  + A dot chart can be used instead, with each point showing the share of residents in the labour force at each age range.

* The reference lines cleared showed that the median age of residents in the labour force was higher in 2019 than 2009. However, it also gives a wrong impression that the value at each age can be interpolated and found. Furthermore, the median age cannot be calculated using the data used in this exercise.
  + The reference lines can be removed to avoid confusion.

* The lead-in paragraph talks about the labour force participation rate. However, we cannot tell from the data visualisation how the labour force participation rate in 2019 differs from 2009.
  + The labour force participation rate can be used as the size for each point on the dot chart i.e. bigger point implies higher labour force participation rate at the age range. We can also include the data values under tooltip.

* The title of the data visualisation should not be "resident labour force by age". It will also give the false impression that we can interpolate and find the value at each age.
  + The title can be changed to "Resident Labour Force (%) and Labour Force Participation Rate (%) by Age Range" to illustrate the data given.

## Aesthetics

* The use of two contrasting colours (blue and grey) for the lines and table rows clearly showed the data belonging to the two years.
  + For the improved data visualisation, we can similarly use two contrasting colours for the dot chart and data.

* The multiple labelling of "June 2009" and "June 2019" is not necessary, given the use of colours to differentiate the years.
  + The multiple labels can be removed and a legend can be created to show the colours (for the dot chart and data) that belong to each year.

* The tick marks on the x-axis are wrongly placed, inappropriate and confusing, as age range should be a categorical rather than a continuous variable. This makes it difficult to find the value at each age range on the line chart and gives the wrong impression that we can interpolate and find the value at each age.
  + The tick marks on the x-axis can be removed.

* The data source is properly and clearly labelled at the bottom of the data visualisation.
  + Similarly, we can label the data source clearly in the improved data visualisation.

## Sketch of Proposed Design

Insert image

* The dot chart can show the share of residents in the labour force at each age range without confusing readers that the values can be interpolated at each age.
* The labour force participation rate can be easily compared by looking at the size of the dots for the two years.


# 2.0 Step-by-Step Description of Data Visualisation Preparation

- Data source, import into Tableau
- Data preparation, cleaning
- Create new calculated field, parameter
- Sheet 1, sheet 2, create charts
- Tooltips, details, formatting
- Dashboard, title


# 3.0 Proposed Data Visualisation Using Tableau

Insert image


## Major Observations

* The share of residents aged 55 & over in the labour force rose from 15.6% in 2009 to 24.7% in 2019, with notable rise from 4.60% in 2009 to 7.30% in 2019 for residents aged 60 to 64 and from 1.80% in 2009 to 4.50% in 2019 for residents aged 65 to 69.
* This was partly due to the higher labour force participation rate for residents aged 55 & over, most notably 63.90% in 2019 as compared to 50.60% in 2009 for residents aged 60 to 64, and 46.10% in 2019 as compared to 29.90% in 2009 for residents aged 65 to 69.
* The labour force participation rate was generally higher in 2019 than 2009 for all age ranges except 20 to 24, which was 61.00% in 2019 as compared to 63.50% in 2009. Despite this, the overall share of resident labour force aged 25 to 54 declined from 75.3% to 67.5%.