---
title: "assignment"
description: |
  Assignment as part of Visual Analytics Project titled VISTAS - Visualising Industry Skill TAlent Shifts.
author:
  - name: Louis Chong Jia Jun (louis.chong.2019@mitb.smu.edu.sg)
    url: https://www.linkedin.com/in/louis-chong-jia-jun
date: 03-06-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Install and Launch R Packages

```{r message=FALSE, warning=FALSE}
packages = c('tidyverse', 'readxl')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

# Import Data

```{r}
employment <- read_excel("data/public_use-industry-employment-growth.xlsx", sheet = 4)
skills_need <- read_excel("data/public_use-industry-skills-needs.xlsx", sheet = 4)
skills_penetration <- read_excel("data/public_use-skill-penetration.xlsx", sheet = 4)
country_migration <- read_excel("data/public_use-talent-migration.xlsx", sheet = 4)
industry_migration <- read_excel("data/public_use-talent-migration.xlsx", sheet = 5)
talent_migration <- read_excel("data/public_use-talent-migration.xlsx", sheet = 6)
```

```{r}
head(industry_migration)
```

```{r}
industry_match <- merge(employment, industry_migration, by = c("country_name", "wb_region", "wb_income", "isic_section_name", "industry_id", "industry_name"))
industry_match <- industry_match[-c(7:8, 14:15)]
```

```{r}
head(industry_match)
```

```{r}

```



